WIP: Fix repo update order (Director first) in demo and tests
uptane/obsolete-reference-implementation pull request #179
Opened 2019-03-25 22:17 UTC by awwad

This is a WIP (triggers testing, will require demo check).

For both Uptane Standard conformance and the resolution to the
Timeserver fast-forward attack (discussed in #173), it is important for clients to
update Director Repository metadata before Image Repository
metadata.

This PR makes sure that the Director repo is updated first
in the Uptane demo and in the tests, by updating pinned.json
and the various templates for pinned.json.

2019-03-26 22:09 UTC, awwad commented
The actual content of this PR has to be dug out of PR #173....  It's a movement from just calling `updater.refresh()` in `fully_validate_metadata()` to calling a new function `refresh_toplevel_metadata_from_repositories()`, which will make multiple calls to `updater.refresh()` to ensure that the Director repository is called first.

2019-03-29 16:12 UTC, lukpueh requested changes
The function name refactor and explicit update order looks good to me. 

Just to make sure, changing the order in the metadata is only to not confuse the human reader, right? At least that's what the code and the PR description suggest. I am just asking, because the commit message in 6d91773ec08ce1e3ef3b73650902ebb9b9018356 reads differently, i.e. that it does make a difference to the update order.

Also, could it be that you missed [`tests/test_data/pinned.json`](https://github.com/uptane/uptane/blob/9ff20fddafffaede7261c52c643cc289870d9c39/tests/test_data/pinned.json)?

2019-03-29 16:19 UTC, awwad commented
> Just to make sure, changing the order in the metadata is only to not confuse the human reader, right? At least that's what the code and the PR description suggest. I am just asking, because the commit message in [6d91773](https://github.com/uptane/uptane/commit/6d91773ec08ce1e3ef3b73650902ebb9b9018356) reads differently, i.e. that it does make a difference to the update order.

My first take (when the commit message went in) was that the order was relevant, but it is not, so the change persists in order to prevent confusion, yes.  I'll edit the commit history to remove the old comment.

> Also, could it be that you missed [`tests/test_data/pinned.json`](https://github.com/uptane/uptane/blob/9ff20fddafffaede7261c52c643cc289870d9c39/tests/test_data/pinned.json)?

Looks like.  :)  Fixing.

2019-03-29 16:25 UTC, lukpueh approved these changes

2019-03-29 16:52 UTC, merged