Log whether or not the keyid matches in a VVM sig check
uptane/obsolete-reference-implementation pull request #70
Opened 2017-04-13 15:34 UTC by awwad

When validating the Primary's signature on a Vehicle Version
Manifest, first check and see if the keyid provided in the
signature matches the keyid logged in the inventory database
for that Primary ECU, and if not, log a message indicating
that before proceeding to the signature validity check.

This is NOT security relevant. Code already tests whether
or not the signature is a valid signature by the correct
key. The only difference is that before, it was not clear
if the signature was from the wrong key instead of just
being a bad signature from the right key.

2017-04-26 15:34 UTC, vladimir-v-diaz commented
Note that there are conflicts in this pull request that must be resolved.

In addition, the `director.py` module that is modified in this pull request references `demo_director_svc.py`, which does not exist in the codebase.

2017-04-26 15:46 UTC, vladimir-v-diaz requested changes

2017-04-26 15:46 UTC, vladimir-v-diaz commented on uptane/services/director.py
> +          'unless the key is the same but the keyid differently hashed.')
I think it will assist debuggers if the 'keyid_used_in_signature' and the expected keyid are included in the logged message.

2017-04-28 16:43 UTC, awwad commented
This should no longer be merged, as the affected code has been removed.

That said, we should consider adding this code to the new location of this code, in uptane.common.verify_signature_over_metadata.

2017-05-10 20:04 UTC, awwad commented on uptane/services/director.py
> +          'unless the key is the same but the keyid differently hashed.')
Good point. Added.

2017-05-10 20:09 UTC, awwad commented
Rebased and no longer in conflict. Comment addressed. Testing and will merge.

2017-05-10 21:27 UTC, merged