Work around pip git-based reinstall issue by specifying TUF branch
uptane/obsolete-reference-implementation pull request #78
Opened 2017-04-17 18:01 UTC by awwad

and instruct users to run the reinstall command when updating Uptane, so as to avoid TUF version incompatibility.

We'll use 
`pip install --force-reinstall -r dev-requirements`

and in dev-requirements, we'll specify the develop branch.

See [this issue](https://github.com/pypa/pip/issues/4448) in pip.

2017-04-17 18:23 UTC, vladimir-v-diaz requested changes

2017-04-17 18:23 UTC, vladimir-v-diaz commented on README.md
> +When updating Uptane code, please reinstall its dependencies, as the corresponding TUF fork may be updated: `pip install --force-reinstall -r dev-requirements.txt`
It's easier on the eyes if the command were on its own separate line. I recommend starting a new line after `updated:`

2017-04-17 18:23 UTC, vladimir-v-diaz commented on README.md
> +Note that the demonstration now operates using ASN.1 / DER format and encoding for metadata files by default. This can be switched back to JSON (which is human readable) by changing the tuf.conf.META
To enable JSON metadata, how should the option be set? `json`?  Make it clear in the instructions.  We should also list the available values for this option in `uptane/__init__.py`

2017-04-18 21:23 UTC, awwad commented
Addressed comments

2017-04-24 14:18 UTC, vladimir-v-diaz commented
I tried using the pip reinstall command that this PR instructs the user to run, and my py2.7 and py3.5 environments appear to update correctly.

```nstalling collected packages: tuf, uptane
  Running setup.py develop for tuf
    warning: no files found matching '*.pem' under directory 'tests'
    Creating /home/vlad/projects/vladforks/tmp/uptane/env3/lib/python3.5/site-packages/tuf.egg-link (link to .)
    tuf 0.10.0 is already the active version in easy-install.pth
    Installing basic_client.py script to /home/vlad/projects/vladforks/tmp/uptane/env3/bin
    
    Installed /home/vlad/projects/vladforks/tmp/uptane/env3/src/tuf
  Running setup.py develop for uptane
    Creating /home/vlad/projects/vladforks/tmp/uptane/env3/lib/python3.5/site-packages/uptane.egg-link (link to .)
    uptane 0.1.0 is already the active version in easy-install.pth
    
    Installed /home/vlad/projects/vladforks/tmp/uptane
Successfully installed tuf uptane
Cleaning up...
```

2017-04-24 14:19 UTC, vladimir-v-diaz commented
The re-installation command in the PR summary is missing a `.txt`
```
pip install --force-reinstall -r dev-requirements
```

2017-04-24 14:19 UTC, vladimir-v-diaz commented
This PR is good to merge!

2017-04-26 19:16 UTC, merged